### ISSUE TITLE
Include OpenColorIO configurations with DJV

### ISSUE THREAD

**Issue by NNois** [darbyjohnston/DJV#142]
Hi,
I use DJV for a very long, it's a really useful tool !
Today I tried the 2.0.3 beta
My main problem is that now, .exr files opens with the wrong color profile like if a gamma curve was applied... Images a very contrasted. I think linear images like .exr files should be viewed as linear files or something like that ;-)
Plus, in the main interface I only have the choice for sRGB and haven't any "linear" option in the dropdown.
Tested on Latest Ubuntu

Cheers

**Comment by darbyjohnston** [comment]
Hi,

Sorry about that, the color functionality is in a bit of a transition with the new 2.0 version. I've switched to using OpenColorIO which takes a bit of manual setup; basically download this set of OpenColorIO configurations:

http://github.com/imageworks/OpenColorIO-Configs/tarball/master

Unpack it somewhere and you will find inside directories like "aces_1.0.3", "spi-vfx", etc. Choose one (like "spi-vfx") and then set the OCIO environment variable to point to the .ocio file inside the directory, like:

export OCIO="/home/darby/ocio/spi-vfx/config.ocio"

Now when you start DJV you should see a bunch of different color spaces you can set, either in the settings dialog, or the "Color Space Widget" from the "Image" menu. Here's the OpenColorIO docs for what the different color spaces are for:

https://opencolorio.org/configurations/spi_vfx.html

For the next version I'll bundle some of the color spaces with DJV so these manual steps won't be necessary.

Darby

**Comment by NNois** [comment]
Cool !
Would the system will be able to auto assume color profile, like exr=linear, jpg=sRGB etc ?

**Comment by darbyjohnston** [comment]
Yes, I'll set it up so that you can assign profiles for each file format, with reasonable defaults for OpenEXR, DPX, etc. I'm hoping to get the release with this new functionality out by the end of the month.

Darby

**Comment by darbyjohnston** [comment]
I've bundled the sample OpenColorIO configurations "nuke-default", "spi-anim", and "spi-vfx" with DJV so that the manual setup isn't needed anymore. I didn't include the ACES color configurations due to size, but they can be downloaded separately and easily added through the UI. I also changed the UI a bit to put all the color space controls in one place (instead of split between the color space widget and settings dialog). This functionality will be available with the next release, hopefully in a couple of weeks.

![DJV Color Space](https://user-images.githubusercontent.com/8532558/64911524-a4a37800-d6d7-11e9-8860-ccd5c1ca9a19.PNG)
