### ISSUE TITLE
2.0.5 doesn't show file/folder names in Cyrillics

### ISSUE THREAD

**Issue by prokoudine** [darbyjohnston/DJV#173]
I can view file/folder names using the Latin alphabet just fine, but not Cyrillics. It's all empty space where letters are supposed to be.

**Comment by darbyjohnston** [comment]
Hi,

Thanks for reporting this; do you have the language in the settings set to English or another language?

Darby

**Comment by prokoudine** [comment]
Switching to Russian fixes it, although I can't for the life of me imagine why being able to display Cyrillics depends on UI language :)

By the way, Russian translation looks automatically translated. Do you accept PRs for it, or is there a dedicated translator already?

**Comment by darbyjohnston** [comment]
The language setting also changes the font, and unfortunately the font used for English ("Barlow") has limited support for other languages. When you switch to Russian it uses the "Noto" font which does have support for Cyrillics, though of course I hadn't thought about the case where you have your UI in English and files in another language. :) I'll talk to the designer about unifying on "Noto" so that it will work either way.

Yes, the translations are machine generated so there may be some surprises there, sorry! I would welcome any fixes to them, though the workflow is not great right now and hasn't been tested well:
https://darbyjohnston.github.io/DJV/contributing.html#Translations

**Comment by prokoudine** [comment]
This looks like a JSON file that saves Unicode data in code points :)

```
    {
        "source": "Child Added", 
        "text": "\u0420\u0435\u0431\u0435\u043d\u043e\u043a \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d", 
        "id": "ChildAdded", 
        "description": ""
    }, 
```

That's not exactly easily editable :)

Any chance you could consider switching to gettext? The benefits are:

- handles plural forms in most existing languages
- has "fuzzy" status for original messages that have been changed since the last translation, so it's easy to see what need updating
- allows adding comments for translators
- every message refers to a specific line in source code, which gives you idea where the text can be seen
- still editable in a text editor
- a wide choice of specialized editors

Here's a typical entry in a translation:

```
#: add_route_dialog.cc:82 add_route_dialog.cc:245
msgid "Audio Busses"
msgstr "Звуковые шины"
```

Gettext operates on text files for editing translations and binary versions of those files to be used by an actual application. This might be a bit of a bummer for you, since your system allows loading a translation file from a local folder which could be handy.

**Comment by darbyjohnston** [comment]
I mentioned the workflow was not great. :)

I'm not very familiar with gettext, this is the GNU software? While I respect the GNU project a lot I have been hesitant to add LGPL/GPL libraries to DJV since it is BSD licensed and I would like to keep the licensing simple. Also taking a quick look it uses autoconf for the build system which I am allergic to and makes compiling for Windows difficult. Do you know of any other alternatives to gettext?

**Comment by darbyjohnston** [comment]
I talked with the designer about switching the default font to Noto and he is OK with that; it looks like there is also a request to add Cyrillic to the Barlow font, so it may be possible to switch back at some point:
https://github.com/jpt/barlow/issues/16

**Comment by prokoudine** [comment]
Well, sadly, I can't think of any sensible replacement for gettext immediately. I guess I'm too spoiled :) Will have to research.

**Comment by darbyjohnston** [comment]
I've changed the font to Noto which will fix this bug, and opened a separate issue for improving the translation workflow:
https://github.com/darbyjohnston/DJV/issues/181
