### ISSUE TITLE
Hosting sample files for testing/troubleshooting

### ISSUE THREAD

**Issue by fsiddi** [darbyjohnston/DJV#179]
I'd like to suggest setting up a basic web server where some "standard" files could be hosted. This would make troubleshooting and issue reporting easier and more consistent. Are you open to setting up a basic website, or google cloud storage or even just a dropbox folder? I'm available to provide mov, mkv, tif, png and exr image sequences from open movies.

**Comment by darbyjohnston** [comment]
They could also be hosted on SourceForge, there are actually some sample images there from quite awhile back:
https://sourceforge.net/projects/djv/files/djv-images/

Are these files already being publicly host by open movies? If so, maybe a collection of links to them in the docs would be sufficient?

**Comment by fsiddi** [comment]
The files I'm suggesting would be a subset of the open movies project. Such collection is not available at the moment, but I can make it if you are interested.

Personally I'm not a huge fan of SourceForce (lots of clutter over there, and their download system currently does not work with the uBlock ad blocker). I think DJV would definitely benefit from having its own web domain.

**Comment by darbyjohnston** [comment]
Doing some searching It looks like GitHub also has an option for storing large files:
https://git-lfs.github.com/

That might be a nice solution since everything could be managed in the same place.

**Comment by fsiddi** [comment]
Thought about it, but there are quite [some limitations](https://help.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage ) for it (max 1GB storage, 1GB bandwidth).

**Comment by darbyjohnston** [comment]
Hmm, it looks like the free option for GitHub is fairly small, just 1GB storage / 1GB bandwidth. Buying additional storage is $5 / month for 50GB storage / 50GB bandwidth.

What would an estimate be for the amount of storage needed? Let's start with a 1920x1080 100 frame image sequence for a few file types:

DPX = 791MB
EXR = 1.16GB
JPEG = 46MB
16-bit TIFF = 1.16GB
MP4 = 20MB
ProRes = 133MB

So about 3.4GB. It would also be nice to test variations of the file types, like different compression types, number of channels, etc. Let's say 6 variations (greyscale, greyscale + alpha, rgb, rgba, compressed and non-compressed). That will vary the sizes a bit, but let's just keep it easy and multiply by 6, so about 20.4GB. I could see that easily doubling again adding more things like multi-layer EXRs and new file types like DNG, CineForm, REDCode Raw, etc. That's still under 50GB, so $5/month which isn't bad.

The bandwidth rate gets tricky since it's not sure how many people will download the files. Even with the first size at 3.4GB without any variations only 14 people could download the entire set at the $5/month rate (50GB). Though people might only be interested in certain file types and not need the whole set.

I'm not a big fan of the ads either but the nice thing about SourceForge is that it is free. On the other hand maybe trying out GitHub LFS at $10 or $15 a month could be a good test.

**Comment by fsiddi** [comment]
I rather suggest a cheap Digital Ocean droplet at $10/mo for 250GB storage and 1TB traffic. In the meantime I'll make a selection of files available in a few formats, which can then be converted further.

**Comment by darbyjohnston** [comment]
Thanks, after some thought I'd like to start with hosting the files at SourceForge. I don't think their ads are over the top and I appreciate that they have hosted DJV for the last 15 years. If the traffic or file sizes turns out to be too much for SourceForge we can try another service later.

I'll upload a couple sequences of live-action footage as a test. If you can provide a rendered EXR sequence in linear color space that would be helpful, especially multi-layer files.

**Comment by darbyjohnston** [comment]
Well, unfortunately it looks like SourceForge won't work either; they also have a 1GB maximum file size and while they don't have a hard bandwidth cap they advise being "neighborly" about downloads which is a bit vague.

After some more thought I have an alternate proposal which is to write a test pattern generator that can produce an animation similar to this:
https://www.youtube.com/watch?v=Srmdij0CU1U

It should be fairly quick to write and I think will actually be more useful than test footage since it could generate a variety of different image sequences based on options like output resolution, number of frames, number of channels, and file format. So for example you could have it write out 1000 4K RGBA TIFF frames to test high-resolution playback, which is like 75GB of data. The simple animation may also be more useful than regular footage for spotting issues with playback speed and judder. What do you think?

**Comment by darbyjohnston** [comment]
I've added a new command-line tool called "djv_test_pattern" that can render out a simple animation with settings for the number of frames, image resolution, image type, and file format. For example this command-line will render out 100 frames of UHD resolution RGB 16-bit TIFF files:
`djv_test_pattern test.1.tif -size '3840 2160' -type RGB_U16`

The animation consists of a number of vertical bars that slowly animate horizontally across the frame, which should be good for spotting problems with smooth playback. Other animations can be added in the future for additional troubleshooting.
