### ISSUE TITLE
[BUILD] Ninja CMake Build Fails with $ Literal

### ISSUE THREAD

**Issue by sobotka** [darbyjohnston/DJV#191]
Not sure what the exact issue in the CMakeLists is, but it seems to be related to literals. Completes fine after the `cmake -G Ninja ./path/to/source` but then `ninja` bombs out with the string literal issue.

Should be an easy fix, just not a cmake guru.

**Comment by darbyjohnston** [comment]
It looks like replacing $(MAKE) with ${CMAKE_MAKE_PROGRAM} in the CMake files fixes this, though this seems to disable parallel builds for regular make. Even with this fixed there is another error from Nina about missing dependencies which may be caused by how ExternalProject_Add is being used.

Try using parallel make instead (e.g., "make -j 16"), documentation for how to build DJV is here:
https://darbyjohnston.github.io/DJV/build_linux.html

**Comment by darbyjohnston** [comment]
I've modified the CMake files to fix the "$ literal" issue and as part of some unrelated work it looks like the problems with the ExternalProject_Add have gone away. I just tried building with Ninja on Ubuntu and everything seems to be working OK now.
