### ISSUE TITLE
DJV 2.0.5 - System log no scrolling once reloaded

### ISSUE THREAD

**Issue by aberkl** [darbyjohnston/DJV#217]
DO:
- TOOLS > SYSTEM LOG, scroll using mouse wheel or CURSOR UP/DOWN or PGUP/PGDOWN -> works as expected
- click "Reload"

HAPPEN:
- scroll using mouse wheel or CURSOR UP/DOWN or PGUP/PGDOWN no longer works

SHOULD:
- work

NOTES:
- closing and re-opening SYSTEM LOG solves the issue

**Comment by darbyjohnston** [comment]
This is related to:
https://github.com/darbyjohnston/DJV/issues/218

Except in this case the "Reload" button has the text focus and is receiving the keyboard and mouse wheel events. Since the button doesn't handle those events they should instead be passed on to the widget the mouse is hovering over.

**Comment by darbyjohnston** [comment]
OK, I think this is fixed now; if a widget has the text focus but doesn't accept the key press event, the event will be forwarded on to the hovered widget (in this case the scroll area in the system log).
