### ISSUE TITLE
Cannot use Play Every Frame and (Playback ping-pong or Playback once) at the same time

### ISSUE THREAD

**Issue by PiOverFour** [darbyjohnston/DJV#242]
When using _Play Every Frame_, the playback is looped even if _Ping-pong_ or _Playback once_ is selected. It happens whether _Memory Cache_ is enabled or not.

**Comment by darbyjohnston** [comment]
Hi, sorry for the delay, i just checked in a change that should fix this. It works OK in my test cases but if you have some time to try it out that would be great.

One caveat is that ping-pong playback is still broken on movie files until this issue is fixed:
https://github.com/darbyjohnston/DJV/issues/152

**Comment by PiOverFour** [comment]
Hi, no problem. It’s working on the sequences I previously tested with, thanks!
It seems that you are out of issues for the 2.0.6 milestone… ;)

**Comment by darbyjohnston** [comment]
Great, thanks for testing it out!

Yes, it's nice to finally see 2.0.6 at 100% :) I'll try building the distribution packages tomorrow and if everything goes well, I'll make the release.

**Comment by darbyjohnston** [comment]
OK, I just made the 2.0.6 release, the distribution packages are uploaded and the source code is tagged.
