### ISSUE TITLE
Request: GUI outside visible content area

### ISSUE THREAD

**Issue by hced** [darbyjohnston/DJV#355]
I'd like to request an option to place Playbar and Menu _outside_ the picture area. In other words, so that it doesn't cover the picture when you move the mouse during playback.

Edit: I just realized that you can sort of achieve this by pressing the "Frame image within the view" button, but when zooming in, the GUI still covers the image and this is where I'd like to have the option to always keep GUI outside the image.

**Comment by darbyjohnston** [comment]
Hi,

Yes, the "frame" option was meant to help alleviate this issue but since it has come up a number of times I should probably change the design so that the timeline (and menu bar) do not overlap the image. I'm also going back to a single timeline (instead of one for each clip), and will make this change as part of that work:

https://github.com/darbyjohnston/DJV/issues/347

**Comment by darbyjohnston** [comment]
I've changed the UI layout so that the menu and timeline don't overlap the image anymore and will include this with the next release. The original intention of the overlap was to help with full screen viewing when the UI faded away, but in practice it didn't work as well as I had hoped. To replace it I've added a dedicated full screen mode ("presentation" mode https://github.com/darbyjohnston/DJV/issues/348), that will hide the menu and timeline for viewing just the image.
